Create Houses DB
dovbush-olha/the-magic-place pull request #35
Opened 2023-04-28 09:46 UTC by dovbush-olha

2023-04-28 10:39 UTC, MarynaPyvovar requested changes

2023-04-28 13:38 UTC, dovbush-olha commented on client/DB/Houses.ts
> +      'МакҐонагол є останньою відомою очільницею Гріффіндору. Вона покинула посаду, коли перейняла посаду директора Хогвартсу в 1998 році після Другої світової війни чаклунів, і немає жодних записів
Thank you, also will be fixed

2023-04-28 13:40 UTC, denyslozynskyi approved these changes

2023-04-29 14:32 UTC, dovbush-olha commented on client/DB/Houses.ts
> +      "У під час інтерв'ю Дж.К. Роулінг зізналася, що коли проходила відбір на Поттерморі, вона виявилася Гріффіндорцем! Вона була трохи здивована і сказала, що насправді має слабкість до Хаффлпафу."
Thank you, yes, it is important

2023-05-03 07:56 UTC, merged